name: "ai-mvp-db"

version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_ecom
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ecomdb
    ports:
      - "5432:5432"
    volumes:
      - ./db_init_ecom/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql

  mongo:
    image: mongo:6
    container_name: mongo_ecom
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db_init_ecom/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js

  mysql:
    image: mysql:8.0
    container_name: mysql_ecom
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecomdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_init_ecom/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
